# Changelog

# ⚠⚠ Please follow the format provided ⚠⚠
#  - name: version number
#    changes:
#      - title: Title of changes
#        categories: [CHANGED AREA]
#        authors: [YourName]


releases:
  - name: 3.4.4
    changes:
      - title: Added reload-button to developer configuration
        categories: [Core]
        authors: [Revyn112]
      - title: Improved handling of checkIncompatibleAddOns
        categories: [Core]
        authors: [Revyn112]
      - title: Avoid caching of the installer configuration
        categories: [Core]
        authors: [Cdr_Maverick]
      - title: Reset-to-default button for developer configuration
        categories: [Core]
        authors: [Gaudv]
      - title: fix move people to new installer config url
        categories: [Core]
        authors: [FoxtrotSierra]
  - name: 3.4.3
    changes:
      - title: Change installer configuration to Cloudflare
        categories: [Core]
  - name: 3.4.2
    changes:
      - title: Fix printer selection not working in some cases
        categories: [UI]
        authors: [saschl]
      - title: Add possibility of getting latest track versions from fragmenter distribution manifest
        categories: [Core]
        authors: [holland]
      - title: Preparation work for new Simbridge resources directory
        categories: [Core]
        authors: [saschl]
  - name: 3.4.1
    changes:
      - title: Update installer default data for addon sources
        categories: [Core]
        authors: [alepouna]
      - title: Shortcut keys no longer override other applications shortcuts
        categories: [UI]
        authors: [alepouna]
      - title: Improve detection of MSFS installation
        categories: [Core]
        authors: [FoxtrotSierra]
  - name: 3.4.0
    changes:
      - title: Add a button to the error dialog to copy error messages to clipboard
        categories: [UI]
        authors: [Cdr_Maverick]
  - name: 3.3.8
    changes:
      - title: Bump fragmenter to v0.7.4 - reduce chance of downloading corrupt archives
        categories: [Core]
        authors: [holland]
      - title: Fix some errors while checking for incompatible addons
        categories: [Logic]
        authors: [Cdr_Maverick]
      - title: Fix git install detection
        categories: [Logic]
        authors: [Eearslya]
  - name: 3.3.7
    changes:
      - title: Fix silent error while checking for free disk space on certain Windows installations
        categories: [Logic]
        authors: [holland]
  - name: 3.3.6
    changes:
      - title: Fix bugged free disk space modal for addons with unknown size info
        categories: [Logic]
        authors: [holland]
  - name: 3.3.5
    changes:
      - title: Fix free disk space check not following symbolic links
        categories: [Logic]
        authors: [holland]
      - title: Fix free disk space check not also verifying temporary directory free space
        categories: [Logic]
        authors: [holland]
      - title: Add banner when a non-default configuration URL is used
        categories: [Core]
        authors: [Cdr_Maverick]
      - title: Update bundled content to reflect current content on the server
        categories: [Addons]
        authors: [holland]
  - name: 3.3.4
    changes:
      - title: Bump fragmenter to v0.7.3
        categories: [Core]
        authors: [holland]
  - name: 3.3.3
    changes:
      - title: Added check for incompatible add-ons
        categories: [Addons]
        authors: [Cdr_Maverick]
      - title: Remove temporary folders from previous installers
        categories: [Logic]
        authors: [holland]
      - title: Improve the clarity of some error messages
        categories: [UI]
        authors: [holland]
      - title: Minor progress UI fixes
        categories: [UI]
        authors: [holland]
      - title: Fix some state management during install process
        categories: [Core]
        authors: [holland]
      - title: Bump fragmenter to v0.7.2
        categories: [Core]
        authors: [holland]
  - name: 3.3.2
    changes:
      - title: Do not crash if some temporary folders cannot be removed
        categories: [Core]
        authors: [holland]
  - name: 3.3.1
    changes:
      - title: Do not fail install if free disk space check fails
        categories: [Core]
        authors: [holland]
      - title: Fix Sentry DSN key in production releases
        categories: [Core]
        authors: [holland]
  - name: 3.3.0
    changes:
      - title: New backend system providing more reliable downloads and less RAM usage
        categories: [Core]
        authors: [holland]
      - title: Package/install size checks before installing or updating an addon
        categories: [Core]
        authors: [holland]
      - title: Improved install progress UI to show more relevant information
        categories: [UI]
        authors: [holland]
      - title: Seamless updates of installer content
        categories: [Core]
        authors: [holland, Mav]
      - title: Uninstalling will no longer freeze the app for a short amount of time
        categories: [Core]
        authors: [holland]
      - title: Errors now show a code that can be given to support for quick diagnostic
        categories: [Core]
        authors: [holland]
      - title: External apps that the installer can close can now be stopped from the modal that appears if running programs block an install or update
        categories: [Core]
        authors: [holland]
      - title: SimBridge no longer required to be closed when updating the A32NX
        categories: [Addons]
        authors: [holland]
  - name: 3.2.2
    changes:
      - title: Update dependency to mitigate potential security issue
        categories: [Core]
        authors: [holland]
  - name: 3.2.1
    changes:
      - title: Fix detection of A32NX experimental version as development versions
        categories: [Addons]
        authors: [FoxtrotSierra]
  - name: 3.2.0
    changes:
      - title: Add FlyByWire Simulations SimBridge
        categories: [Addons]
        authors: [holland, Erick]
      - title: Add support for addon background services
        categories: [Core]
        authors: [holland]
      - title: Improve UI for open applications preventing addon install, update or removal
        categories: [UI]
        authors: [holland]
      - title: Add SimBridge configuration UI
        categories: [Addons]
        authors: [holland, Erick]
      - title: Add customisable temporary folder setting
        categories: [Logic]
        authors: [marinofranz, FoxtrotSierra]
  - name: 3.1.0
    changes:
      - title: Add Salty Simulations 74S
        categories: [Addons]
        authors: [Ninjo, FoxtrotSierra]
      - title: Fix installer crashing due to inexisting page
        categories: [Core]
        authors: [FoxtrotSierra]
      - title: Prevent uninstalling while MSFS is open
        categories: [Logic]
        authors: [FoxtrotSierra]
      - title: Prevent updating or uninstalling while MCDU Server is running
        categories: [Logic]
        authors: [FoxtrotSierra]
      - title: Fix smaller design issues on ≤1080p
        categories: [UI]
        authors: [holland]
  - name: 3.0.0
    changes:
      - title: Fallback to full install after too many retries on a module
        categories: [Fragmenter]
        authors: [FoxtrotSierra]
      - title: Complete redesign of the installer UI
        categories: [UI]
        authors: [holland, Erick, Kevin, FoxtrotSierra, GhostEagle68]
      - title: Add ReleaseNotes Tab
        categories: [Features]
        authors: [Erick]
      - title: Add publisher quicklinks to the sidebar
        categories: [UX]
        authors: [holland, Erick, GhostEagle68]
      - title: Add autostart functionality
        categories: [Features]
        authors: [Erick]
      - title: Add uninstall functionality
        categories: [Logic]
        authors: [FoxtrotSierra]
      - title: Fix only last started download abortable on parallel downloads
        categories: [Logic]
        authors: [FoxtrotSierra]
      - title: Search for updates every 5 minutes
        categories: [Logic]
        authors: [FoxtrotSierra]
  - name: 2.2.2
    changes:
      - title: Enable experimental version for A32NX
        categories: [Addons]
        authors: [holland]
  - name: 2.2.1
    changes:
      - title: KFBW is now visible to everyone
        categories: [Addons]
        authors: [FoxtrotSierra]
  - name: 2.2.0
    changes:
      - title: Prepare Installer to be able to handle multiple addons
        categories: [Logic]
        authors: [FoxtrotSierra]
  - name: 2.1.1
    changes:
      - title: Fix error during configuration of community directory
        categories: [Logic]
        authors: [FoxtrotSierra]
      - title: Disable experimental version for A32NX
        categories: [Addons]
        authors: [FoxtrotSierra]
  - name: 2.1.0
    changes:
      - title: Add ability to change date layout
        categories: [UX]
        authors: [FoxtrotSierra]
      - title: Add progress bar to taskbar tab to show installation progress
        categories: [UX]
        authors: [Erick]
      - title: Add ability to show third party licenses
        categories: [Logic]
        authors: [nistei]
      - title: Add Synaptic Simulations A22X placeholder
        categories: [Addons]
        authors: [MikeRomaa]
  - name: 2.0.1
    changes:
      - title: Fix error during configuration of settings on first installation
        categories: [Logic]
        authors: [nistei]
      - title: Change link to experimental guide
        categories: [Addons]
        authors: [FoxtrotSierra]
  - name: 2.0.0
    changes:
      - title: Installation method changed from Electron-Forge/Squirel to electron-builder/NSIS to prevent future memory leaks during update
        categories: [Logic]
        authors: [holland, FoxtrotSierra]
      - title: Remove converted livery packages if conversion failed
        categories: [Logic]
        authors: [holland]
      - title: "Rename #help to #support to adopt current Discord channel naming"
        categories: [UI]
        authors: [SjotgunSjonnie, FoxtrotSierra]
      - title: Request the user to set 'Community' folder manually if it cannot be found, fixes error message
        categories: [Logic]
        authors: [FoxtrotSierra]
      - title: Update 'Experimental' version text for A32NX
        categories: [Addons]
        authors: [FoxtrotSierra]
  - name: 1.2.0
    changes:
      - title: Complete redesign of the installer
        categories: [UI]
        authors: [holland, FoxtrotSierra]
      - title: Add livery conversion tool
        categories: [Logic]
        authors: [holland]
      - title: Cleanup of old temporary directories on installer close and startup
        categories: [Logic]
        authors: [nistei]
  - name: 1.1.4
    changes:
      - title: Improved error prevention while downloading an update
        categories: [Logic]
        authors: [nistei]
      - title: Fix click on cancel causing a retry
        categories: [Logic]
        authors: [nistei]
  - name: 1.1.3
    changes:
      - title: Fix downloads failing in encrypted directories
        categories: [Logic]
        authors: [nistei]
      - title: Add retries for failed installs
        categories: [Logic]
        authors: [nistei]
      - title: Add "Experimental" version for A32NX
        categories: [Addons]
        authors: [holland]
  - name: 1.1.1
    changes:
      - title: Fix full downloads broken for some users
        categories: [Logic]
        authors: [nistei]
  - name: 1.1.0
    changes:
      - title: Prevent text selection
        categories: [UI]
        authors: [FoxtrotSierra]
      - title: Prevent image dragging
        categories: [UI]
        authors: [FoxtrotSierra]
      - title: Disable preselecting different versions while downloading
        categories: [Logic]
        authors: [FoxtrotSierra]
      - title: Add Windows notification when download complete
        categories: [UX]
        authors: [FoxtotSierra]
      - title: Add changelog for the installer
        categories: [UX]
        authors: [FoxtrotSierra]
      - title: Fix button styling in settings menu
        categories: [UI]
        authors: [FoxtrotSierra]
      - title: Add report issue button at top right corner of installer
        categories: [UX]
        authors: [Armankir]
      - title: Improved scrollbar color for eased visibility
        categories: [UI]
        authors: [Armankir]
      - title: New version selector UI
        categories: [UI]
        authors: [Marcsoler, Falcon]
      - title: Add warning message for experimental versions
        categories: [UX]
        authors: [Falcon]
      - title: Implement modular download
        categories: [Logic]
        authors: [nistei]
      - title: Fix background image remaining black
        categories: [UI]
        authors: [FoxtrotSierra]
      - title: Fix window icon on hover
        categories: [UI]
        authors: [FoxtrotSierra]
      - title: Fix unknown download state after switching tabs
        categories: [Logic]
        authors: [FoxtrotSierra]
  - name: 1.0.5
    changes:
      - title: Disable offline modal due to issues
        categories: [UX]
        authors: [Falcon]
  - name: 1.0.4
    changes:
      - title: Change CDN (download server)
        categories: [Logic]
        authors: [Falcon]
  - name: 1.0.3
    changes:
      - title: Improve 'MSFS is open' logic
        categories: [Logic]
        authors: [Falcon]
  - name: 1.0.2
    changes:
      - title: Kill unnecessary child processes
        categories: [Logic]
        authors: [nistei]
  - name: 1.0.1
    changes:
      - title: Fix side menu install state - @Benjozork (Benjamin Dupont)
        categories: [Logic]
        authors: [holland]
      - title: Change A380X status from 'not installed' to 'not available'
        categories: [UI]
        authors: [Falcon]
      - title: More accurate 'is installed' logic
        categories: [Logic]
        authors: [Falcon]
      - title: Change version name from 'FBW' to 'Custom FBW'
        categories: [UI]
        authors: [Falcon]
  - name: 1.0.0
    changes:
      - title: Initial Release
